# Generated by rust2rpm 25
%bcond_without check

%global crate shadowsocks-rust

Name:           rust-shadowsocks-rust
Version:        1.17.1
Release:        %autorelease
Summary:        Shadowsocks is a fast tunnel proxy that helps you bypass firewalls

License:        MIT
URL:            https://crates.io/crates/shadowsocks-rust
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Shadowsocks is a fast tunnel proxy that helps you bypass firewalls.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%license LICENSE.dependencies
%doc README.md
%{_bindir}/sslocal
%{_bindir}/ssmanager
%{_bindir}/ssserver
%{_bindir}/ssservice
%{_bindir}/ssurl
%{_bindir}/sswinservice

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+aead-cipher-2022-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+aead-cipher-2022-devel %{_description}

This package contains library source intended for building other packages which
use the "aead-cipher-2022" feature of the "%{crate}" crate.

%files       -n %{name}+aead-cipher-2022-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+aead-cipher-2022-extra-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+aead-cipher-2022-extra-devel %{_description}

This package contains library source intended for building other packages which
use the "aead-cipher-2022-extra" feature of the "%{crate}" crate.

%files       -n %{name}+aead-cipher-2022-extra-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+aead-cipher-extra-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+aead-cipher-extra-devel %{_description}

This package contains library source intended for building other packages which
use the "aead-cipher-extra" feature of the "%{crate}" crate.

%files       -n %{name}+aead-cipher-extra-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+dns-over-h3-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+dns-over-h3-devel %{_description}

This package contains library source intended for building other packages which
use the "dns-over-h3" feature of the "%{crate}" crate.

%files       -n %{name}+dns-over-h3-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+dns-over-https-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+dns-over-https-devel %{_description}

This package contains library source intended for building other packages which
use the "dns-over-https" feature of the "%{crate}" crate.

%files       -n %{name}+dns-over-https-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+dns-over-native-tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+dns-over-native-tls-devel %{_description}

This package contains library source intended for building other packages which
use the "dns-over-native-tls" feature of the "%{crate}" crate.

%files       -n %{name}+dns-over-native-tls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+dns-over-native-tls-vendored-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+dns-over-native-tls-vendored-devel %{_description}

This package contains library source intended for building other packages which
use the "dns-over-native-tls-vendored" feature of the "%{crate}" crate.

%files       -n %{name}+dns-over-native-tls-vendored-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+dns-over-tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+dns-over-tls-devel %{_description}

This package contains library source intended for building other packages which
use the "dns-over-tls" feature of the "%{crate}" crate.

%files       -n %{name}+dns-over-tls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+hickory-dns-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+hickory-dns-devel %{_description}

This package contains library source intended for building other packages which
use the "hickory-dns" feature of the "%{crate}" crate.

%files       -n %{name}+hickory-dns-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+ipnet-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ipnet-devel %{_description}

This package contains library source intended for building other packages which
use the "ipnet" feature of the "%{crate}" crate.

%files       -n %{name}+ipnet-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+jemalloc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+jemalloc-devel %{_description}

This package contains library source intended for building other packages which
use the "jemalloc" feature of the "%{crate}" crate.

%files       -n %{name}+jemalloc-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+jemallocator-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+jemallocator-devel %{_description}

This package contains library source intended for building other packages which
use the "jemallocator" feature of the "%{crate}" crate.

%files       -n %{name}+jemallocator-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+local-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+local-devel %{_description}

This package contains library source intended for building other packages which
use the "local" feature of the "%{crate}" crate.

%files       -n %{name}+local-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+local-dns-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+local-dns-devel %{_description}

This package contains library source intended for building other packages which
use the "local-dns" feature of the "%{crate}" crate.

%files       -n %{name}+local-dns-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+local-flow-stat-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+local-flow-stat-devel %{_description}

This package contains library source intended for building other packages which
use the "local-flow-stat" feature of the "%{crate}" crate.

%files       -n %{name}+local-flow-stat-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+local-http-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+local-http-devel %{_description}

This package contains library source intended for building other packages which
use the "local-http" feature of the "%{crate}" crate.

%files       -n %{name}+local-http-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+local-http-native-tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+local-http-native-tls-devel %{_description}

This package contains library source intended for building other packages which
use the "local-http-native-tls" feature of the "%{crate}" crate.

%files       -n %{name}+local-http-native-tls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+local-http-native-tls-vendored-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+local-http-native-tls-vendored-devel %{_description}

This package contains library source intended for building other packages which
use the "local-http-native-tls-vendored" feature of the "%{crate}" crate.

%files       -n %{name}+local-http-native-tls-vendored-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+local-http-rustls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+local-http-rustls-devel %{_description}

This package contains library source intended for building other packages which
use the "local-http-rustls" feature of the "%{crate}" crate.

%files       -n %{name}+local-http-rustls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+local-redir-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+local-redir-devel %{_description}

This package contains library source intended for building other packages which
use the "local-redir" feature of the "%{crate}" crate.

%files       -n %{name}+local-redir-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+local-socks4-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+local-socks4-devel %{_description}

This package contains library source intended for building other packages which
use the "local-socks4" feature of the "%{crate}" crate.

%files       -n %{name}+local-socks4-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+local-tun-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+local-tun-devel %{_description}

This package contains library source intended for building other packages which
use the "local-tun" feature of the "%{crate}" crate.

%files       -n %{name}+local-tun-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+local-tunnel-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+local-tunnel-devel %{_description}

This package contains library source intended for building other packages which
use the "local-tunnel" feature of the "%{crate}" crate.

%files       -n %{name}+local-tunnel-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+log4rs-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+log4rs-devel %{_description}

This package contains library source intended for building other packages which
use the "log4rs" feature of the "%{crate}" crate.

%files       -n %{name}+log4rs-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+logging-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+logging-devel %{_description}

This package contains library source intended for building other packages which
use the "logging" feature of the "%{crate}" crate.

%files       -n %{name}+logging-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+manager-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+manager-devel %{_description}

This package contains library source intended for building other packages which
use the "manager" feature of the "%{crate}" crate.

%files       -n %{name}+manager-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+mimalloc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mimalloc-devel %{_description}

This package contains library source intended for building other packages which
use the "mimalloc" feature of the "%{crate}" crate.

%files       -n %{name}+mimalloc-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+multi-threaded-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+multi-threaded-devel %{_description}

This package contains library source intended for building other packages which
use the "multi-threaded" feature of the "%{crate}" crate.

%files       -n %{name}+multi-threaded-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+qrcode-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+qrcode-devel %{_description}

This package contains library source intended for building other packages which
use the "qrcode" feature of the "%{crate}" crate.

%files       -n %{name}+qrcode-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+replay-attack-detect-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+replay-attack-detect-devel %{_description}

This package contains library source intended for building other packages which
use the "replay-attack-detect" feature of the "%{crate}" crate.

%files       -n %{name}+replay-attack-detect-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+reqwest-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+reqwest-devel %{_description}

This package contains library source intended for building other packages which
use the "reqwest" feature of the "%{crate}" crate.

%files       -n %{name}+reqwest-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rpmalloc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rpmalloc-devel %{_description}

This package contains library source intended for building other packages which
use the "rpmalloc" feature of the "%{crate}" crate.

%files       -n %{name}+rpmalloc-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+security-replay-attack-detect-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+security-replay-attack-detect-devel %{_description}

This package contains library source intended for building other packages which
use the "security-replay-attack-detect" feature of the "%{crate}" crate.

%files       -n %{name}+security-replay-attack-detect-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+server-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+server-devel %{_description}

This package contains library source intended for building other packages which
use the "server" feature of the "%{crate}" crate.

%files       -n %{name}+server-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+service-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+service-devel %{_description}

This package contains library source intended for building other packages which
use the "service" feature of the "%{crate}" crate.

%files       -n %{name}+service-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+snmalloc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+snmalloc-devel %{_description}

This package contains library source intended for building other packages which
use the "snmalloc" feature of the "%{crate}" crate.

%files       -n %{name}+snmalloc-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+snmalloc-rs-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+snmalloc-rs-devel %{_description}

This package contains library source intended for building other packages which
use the "snmalloc-rs" feature of the "%{crate}" crate.

%files       -n %{name}+snmalloc-rs-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+stream-cipher-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+stream-cipher-devel %{_description}

This package contains library source intended for building other packages which
use the "stream-cipher" feature of the "%{crate}" crate.

%files       -n %{name}+stream-cipher-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tcmalloc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tcmalloc-devel %{_description}

This package contains library source intended for building other packages which
use the "tcmalloc" feature of the "%{crate}" crate.

%files       -n %{name}+tcmalloc-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tcmalloc-vendored-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tcmalloc-vendored-devel %{_description}

This package contains library source intended for building other packages which
use the "tcmalloc-vendored" feature of the "%{crate}" crate.

%files       -n %{name}+tcmalloc-vendored-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+trust-dns-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+trust-dns-devel %{_description}

This package contains library source intended for building other packages which
use the "trust-dns" feature of the "%{crate}" crate.

%files       -n %{name}+trust-dns-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+utility-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+utility-devel %{_description}

This package contains library source intended for building other packages which
use the "utility" feature of the "%{crate}" crate.

%files       -n %{name}+utility-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+utility-url-outline-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+utility-url-outline-devel %{_description}

This package contains library source intended for building other packages which
use the "utility-url-outline" feature of the "%{crate}" crate.

%files       -n %{name}+utility-url-outline-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+windows-service-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+windows-service-devel %{_description}

This package contains library source intended for building other packages which
use the "windows-service" feature of the "%{crate}" crate.

%files       -n %{name}+windows-service-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+winservice-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+winservice-devel %{_description}

This package contains library source intended for building other packages which
use the "winservice" feature of the "%{crate}" crate.

%files       -n %{name}+winservice-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires -f winservice

%build
%cargo_build -f winservice
%{cargo_license_summary -f winservice}
%{cargo_license -f winservice} > LICENSE.dependencies

%install
%cargo_install -f winservice

%if %{with check}
%check
%cargo_test -f winservice
%endif

%changelog
%autochangelog
